;;; sumibi-decisions-test.el --- Decisions ambient regression tests -*- lexical-binding: t; -*-
;;; Commentary:
;; No credentials, network, or paid requests are used by these tests.
;;; Code:
(require 'ert)
(unless (require 'popup nil t) (provide 'popup))
(unless (require 'unicode-escape nil t)
  (defun unicode-escape (s) s)
  (defun unicode-escape-to-string (s) s)
  (provide 'unicode-escape))
(unless (require 'deferred nil t) (provide 'deferred))
(unless (require 'dash nil t)
  (defun -filter (fn items) (cl-remove-if-not fn items))
  (defun -map (fn items) (mapcar fn items))
  (provide 'dash))
(require 'sumibi)

(defmacro sumibi-test--decisions-buffer (&rest body)
  "Run BODY with fake async transport, conversion and isolated Sumibi state."
  (declare (indent 0))
  `(let ((sumibi-ambient-enable t) (sumibi-mode t)
         (sumibi-ambient-backend 'decisions) (sumibi-select-mode nil)
         (sumibi-ambient-punctuation-delay 0.5)
         (sumibi-history-stack nil) (sumibi-use-fence nil)
         (sumibi-debug nil) (sumibi-henkan-kouho-list nil)
         (sumibi-decisions-debug nil)
         (sumibi-decisions-batch-window-ms 0)
         (sumibi-api-key-source 'environment)
         (sumibi-provider 'openai)
         (sumibi-init t)
         (sumibi-decisions-max-calls-per-buffer 1000)
         (process-environment (copy-sequence process-environment))
         requests conversions)
     (setenv "OPENAI_API_KEY" "test-key")
     (setenv "SUMIBI_AI_BASEURL" nil)
     (cl-letf (((symbol-function 'sumibi--decisions-http-post)
                (lambda (url headers body timeout callback)
                  (push (list url headers body timeout callback) requests)
                  #'ignore))
               ((symbol-function 'sumibi-get-api-key) (lambda () "test-conversion-key"))
               ((symbol-function 'sumibi-roman-to-kanji-with-surrounding)
                (lambda (roman surrounding n deferred &optional callback)
                  (push (list roman surrounding n deferred callback) conversions)
                  #'ignore)))
              (with-temp-buffer
                (unwind-protect (progn ,@body) (sumibi--decisions-stop))))))

(defun sumibi-test--decisions-answer (request score)
  "Complete fake REQUEST with SCORE."
  (funcall (nth 4 request)
           (json-encode `((answers . ,(vector `((type . "predicate")
                                                (name . "convert_now")
                                                (probability . ,score)))))) nil))

(defun sumibi-test--decisions-batch-answer (request scores &optional reverse-order)
  "Answer REQUEST with SCORES, optionally reversing the response order."
  (let* ((payload (json-parse-string (decode-coding-string (nth 2 request) 'utf-8)))
         (questions (append (gethash "questions" payload) nil))
         (answers (cl-mapcar
                   (lambda (question score)
                     (if (eq score 'refusal)
                         `((type . "refusal") (name . ,(gethash "name" question)))
                       `((type . "predicate") (name . ,(gethash "name" question))
                         (probability . ,score)))) questions scores)))
    (funcall (nth 4 request)
             (json-encode `((answers . ,(vconcat (if reverse-order (reverse answers) answers))))) nil)))

(ert-deftest sumibi-decisions-batch-window-is-fixed-and-retains-all-keystrokes ()
  (should (= (default-value 'sumibi-decisions-batch-window-ms) 200))
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200) timers events
         (sumibi-decisions-debug t))
     (cl-letf (((symbol-function 'run-with-timer)
                (lambda (delay repeat callback &rest _)
                  (push (list delay repeat callback) timers) 'fake-timer))
               ((symbol-function 'cancel-timer) #'ignore)
               ((symbol-function 'sumibi--decisions-log)
                (lambda (format-string &rest args)
                  (push (apply #'format format-string args) events))))
       (sumibi-setup-auto-convert-hook)
       (dolist (char '(?n ?i ?h))
         (sumibi--decisions-pre-command)
         (insert char) (sumibi-check-particle-trigger))
       (should-not requests)
       (should (= (length timers) 1))
       (should (= (caar timers) 0.2))
       (should (= (length sumibi--decisions-collecting) 3))
       (funcall (nth 2 (car timers)))
       (should (= (length requests) 1))
       (let* ((payload (json-parse-string (decode-coding-string (nth 2 (car requests)) 'utf-8)))
              (states (gethash "states" (json-parse-string (gethash "input" payload))))
              (questions (gethash "questions" payload)))
         (should (equal (mapcar (lambda (state) (gethash "text" state)) (append states nil))
                        '("n" "ni" "nih")))
         (should (= (length questions) 3))
         (should (string-match-p "Ignore every other state" (gethash "instructions" (aref questions 0)))))
       (sumibi-test--decisions-batch-answer (car requests) '(0.1 0.3 0.4) t)
       (should (= (cl-count-if (lambda (event) (string-prefix-p "score=" event)) events) 3))
       (should-not conversions)
       (should-not sumibi--decisions-inflight)))))

(ert-deftest sumibi-decisions-batch-input-checks-deadline-despite-delayed-timer ()
  (dolist (elapsed-us '(200000 274000))
    (sumibi-test--decisions-buffer
     (let ((sumibi-decisions-batch-window-ms 200)
           (now (seconds-to-time 1000)) callbacks old-deadline)
       (cl-letf (((symbol-function 'current-time) (lambda () now))
                 ((symbol-function 'run-with-timer)
                  (lambda (_delay _repeat callback &rest _)
                    (push callback callbacks) 'fake-timer))
                 ((symbol-function 'cancel-timer) #'ignore))
         (insert "n") (sumibi-check-particle-trigger)
         (setq old-deadline sumibi--decisions-window-deadline)
         (setq now (time-add (seconds-to-time 1000) '(0 0 199000)))
         (insert "i") (sumibi-check-particle-trigger)
         (should-not requests)
         (should (= (length sumibi--decisions-collecting) 2))
         (should (equal old-deadline sumibi--decisions-window-deadline))
         ;; Don't execute the timer: the next input must seal the old window.
         (setq now (time-add (seconds-to-time 1000) (list 0 0 elapsed-us)))
         (insert "h") (sumibi-check-particle-trigger)
         (should (= (length requests) 1))
         (should (= (length sumibi--decisions-collecting) 1))
         (should (equal (plist-get (car sumibi--decisions-collecting) :text) "nih"))
         (should (time-less-p old-deadline sumibi--decisions-window-deadline))
         (should (= (length callbacks) 2))
         ;; A late callback from the old timer must not close the new window.
         (funcall (cadr callbacks))
         (should (= (length sumibi--decisions-collecting) 1))
         (sumibi-test--decisions-batch-answer (car requests) '(0.1 0.2))
         (funcall (car callbacks))
         (should (= (length requests) 2))
         (sumibi-test--decisions-batch-answer (car requests) '(0.3))
         (should-not sumibi--decisions-window-deadline))))))

(ert-deftest sumibi-decisions-batch-input-deadline-seals-while-request-active ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200) (now (seconds-to-time 1000)))
     (cl-letf (((symbol-function 'current-time) (lambda () now))
               ((symbol-function 'run-with-timer) (lambda (&rest _) 'fake-timer))
               ((symbol-function 'cancel-timer) #'ignore))
       (insert "n") (sumibi-check-particle-trigger)
       (sumibi--decisions-flush-window)
       (insert "i") (sumibi-check-particle-trigger)
       (setq now (time-add now '(0 0 274000)))
       (insert "h") (sumibi-check-particle-trigger)
       (should (= (length requests) 1))
       (should (= (length sumibi--decisions-ready-batches) 1))
       (should (= (length sumibi--decisions-collecting) 1))
       (sumibi-test--decisions-batch-answer (car requests) '(0.1))
       (should (= (length requests) 2))
       (sumibi-test--decisions-batch-answer (car requests) '(0.2))
       (sumibi--decisions-flush-window)
       (should (= (length requests) 3))
       (sumibi-test--decisions-batch-answer (car requests) '(0.3))
       (should-not conversions)))))

(ert-deftest sumibi-decisions-batch-applies-only-current-result-and-preserves-undo ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200))
     (sumibi-setup-auto-convert-hook)
     (buffer-enable-undo)
     (dolist (char (string-to-list "nihongo."))
       (insert char) (sumibi-check-particle-trigger))
     (undo-boundary)
     (sumibi--decisions-flush-window)
     (sumibi-test--decisions-batch-answer (car requests) (make-list 8 1.0) t)
     (should (= (length conversions) 1))
     (should (equal (caar conversions) "nihongo"))
     (funcall (nth 4 (car conversions)) '("日本語") nil)
     (should (equal (buffer-string) "日本語。"))
     (undo-only 1)
     (should (equal (buffer-string) "nihongo.")))))

(ert-deftest sumibi-decisions-batch-keeps-next-window-during-network-and-conversion ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200))
     (insert "nihongo") (sumibi-check-particle-trigger)
     (sumibi--decisions-flush-window)
     (let ((first (car requests)))
       (insert ".") (sumibi-check-particle-trigger)
       (sumibi--decisions-flush-window)
       (should (= (length requests) 1))
       (should (= (length sumibi--decisions-ready-batches) 1))
       (sumibi-test--decisions-batch-answer first '(1.0))
       (should-not conversions)
       (should (= (length requests) 2)))
     (sumibi-test--decisions-batch-answer (car requests) '(1.0))
     (should conversions)
     (let ((callback (nth 4 (car conversions))))
       (insert "a") (sumibi-check-particle-trigger)
       (sumibi--decisions-flush-window)
       (should (= (length requests) 2))
       (funcall callback '("日本語") nil)
       (should (equal (buffer-string) "nihongo.a"))
       (should (= (length requests) 3)))
     (sumibi-test--decisions-batch-answer (car requests) '(0.1))
     (should-not sumibi--decisions-ready-batches))))

(ert-deftest sumibi-decisions-batch-split-bounds-request-size-without-dropping ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200))
     (dotimes (_ 35) (insert "a") (sumibi-check-particle-trigger))
     (sumibi--decisions-flush-window)
     (should (= sumibi--decisions-call-count 1))
     (sumibi-test--decisions-batch-answer (car requests) (make-list 32 0.1))
     (should (= sumibi--decisions-call-count 2))
     (sumibi-test--decisions-batch-answer (car requests) (make-list 3 0.1))
     (should (= (length requests) 2))
     (should-not sumibi--decisions-inflight))))

(ert-deftest sumibi-decisions-batch-call-limit-counts-requests-not-states ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200) (sumibi-decisions-max-calls-per-buffer 1))
     (dotimes (_ 3) (insert "a") (sumibi-check-particle-trigger))
     (sumibi--decisions-flush-window)
     (sumibi-test--decisions-batch-answer (car requests) '(0.1 0.2 0.3))
     (should (= sumibi--decisions-call-count 1))
     (insert "b") (sumibi-check-particle-trigger)
     (should-not sumibi--decisions-collecting)
     (should (= (length requests) 1))
     (should (eq sumibi--decisions-last-error 'request-limit)))))

(ert-deftest sumibi-decisions-batch-stop-cancels-window-and-ignores-late-timer ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200) callback)
     (cl-letf (((symbol-function 'run-with-timer)
                (lambda (_delay _repeat fn &rest _) (setq callback fn) 'fake-timer))
               ((symbol-function 'cancel-timer) #'ignore))
       (insert "nihongo") (sumibi-check-particle-trigger)
       (sumibi--decisions-stop)
       (funcall callback)
       (should-not requests)
       (should-not sumibi--decisions-timer)
       (should-not sumibi--decisions-collecting)))))

(ert-deftest sumibi-decisions-batch-rejects-malformed-responses ()
  (dolist (body '("garbage" "{\"answers\":[]}"
                  "{\"answers\":[{\"type\":\"predicate\",\"name\":\"wrong\",\"probability\":1}]}"
                  "{\"answers\":[{\"type\":\"predicate\",\"name\":\"state_0\",\"probability\":2}]}"))
    (sumibi-test--decisions-buffer
     (let ((sumibi-decisions-batch-window-ms 200))
       (insert "nihongo") (sumibi-check-particle-trigger)
       (sumibi--decisions-flush-window)
       (funcall (nth 4 (car requests)) body nil)
       (should-not conversions)
       (should (eq sumibi--decisions-last-error 'invalid-response))
       (should-not sumibi--decisions-inflight)))))

(ert-deftest sumibi-decisions-batch-rejects-duplicate-ids ()
  (should-error
   (sumibi--decisions-batch-scores
    "{\"answers\":[{\"type\":\"predicate\",\"name\":\"state_0\",\"probability\":1},{\"type\":\"predicate\",\"name\":\"state_0\",\"probability\":1}]}" 2)))

(ert-deftest sumibi-decisions-batch-refusal-does-not-hide-other-results ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200))
     (insert "nihongo") (sumibi-check-particle-trigger)
     (insert ".") (sumibi-check-particle-trigger)
     (sumibi--decisions-flush-window)
     (sumibi-test--decisions-batch-answer (car requests) '(refusal 1.0))
     (should (= (length conversions) 1)))))

(ert-deftest sumibi-decisions-batch-settings-change-before-flush-prevents-send ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200))
     (insert "nihongo") (sumibi-check-particle-trigger)
     (setq sumibi-decisions-batch-window-ms 300)
     (sumibi--decisions-flush-window)
     (should-not requests)
     (should-not sumibi--decisions-ready-batches)
     (insert ".") (sumibi-check-particle-trigger)
     (sumibi--decisions-flush-window)
     (should (= (length requests) 1)))))

(ert-deftest sumibi-decisions-batch-switch-to-single-cancels-old-window ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200))
     (insert "nihongo") (sumibi-check-particle-trigger)
     (setq sumibi-decisions-batch-window-ms 0)
     (insert ".") (sumibi-check-particle-trigger)
     (should (= (length requests) 1))
     (should-not sumibi--decisions-timer)
     (should-not sumibi--decisions-collecting))))

(ert-deftest sumibi-decisions-batch-network-failure-releases-next-window ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-batch-window-ms 200))
     (insert "nihongo") (sumibi-check-particle-trigger)
     (sumibi--decisions-flush-window)
     (let ((first (car requests)))
       (insert ".") (sumibi-check-particle-trigger)
       (sumibi--decisions-flush-window)
       (funcall (nth 4 first) nil 'timeout))
     (should (= (length requests) 2))
     (should-not conversions)
     (sumibi-test--decisions-batch-answer (car requests) '(0.1))
     (should (equal (buffer-string) "nihongo.")))))

(ert-deftest sumibi-decisions-default-remains-rules ()
  (should (eq (default-value 'sumibi-ambient-backend) 'rules)))

(ert-deftest sumibi-decisions-backend-is-a-customizable-choice ()
  (should (custom-variable-p 'sumibi-ambient-backend))
  (let ((type (get 'sumibi-ambient-backend 'custom-type)))
    (should (eq (car type) 'choice))
    (should (equal (mapcar (lambda (entry) (car (last entry))) (cdr type))
                   '(rules decisions)))))

(ert-deftest sumibi-decisions-non-openai-connection-shows-error-without-network ()
  (dolist (configuration '((gemini nil) (deepseek nil) (local nil)
                          (openai "https://example.invalid/v1")
                          (openai "https://api.openai.com.example.invalid/v1")
                          (openai "http://api.openai.com/v1")
                          (openai "https://api.openai.com:8443/v1")))
    (sumibi-test--decisions-buffer
     (let ((sumibi-provider (car configuration)) messages)
       (setenv "SUMIBI_AI_BASEURL" (cadr configuration))
       (cl-letf (((symbol-function 'message)
                  (lambda (format-string &rest args)
                    (push (apply #'format format-string args) messages)))
                 ((symbol-function 'sumibi--decisions-api-key)
                  (lambda () (ert-fail "Unsupported connection read credentials"))))
         (sumibi-setup-auto-convert-hook)
         (insert "nihongo.") (sumibi-check-particle-trigger)
         (should-not requests)
         (should (= sumibi--decisions-call-count 0))
         (should (= (length messages) 1))
         (should (string-match-p "OpenAI以外" (car messages)))
         (should (eq sumibi--decisions-last-error 'unsupported-provider)))))))

(ert-deftest sumibi-decisions-connection-change-cancels-and-preserves-input ()
  (sumibi-test--decisions-buffer
   (insert "nihongo.") (sumibi-check-particle-trigger)
   (setenv "SUMIBI_AI_BASEURL" "https://example.invalid/v1")
   (sumibi-test--decisions-answer (car requests) 0.95)
   (should-not conversions)
   (should-not sumibi--decisions-inflight)
   (should (equal (buffer-string) "nihongo."))
   (setenv "SUMIBI_AI_BASEURL" nil)
   (sumibi-check-particle-trigger)
   (should (= (length requests) 2))))

(ert-deftest sumibi-decisions-rules-backend-does-not-require-openai ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-provider 'local) (sumibi-ambient-backend 'rules))
     (sumibi-setup-auto-convert-hook)
     (insert "hello") (sumibi-check-particle-trigger)
     (should-not sumibi--decisions-last-error)
     (should-not requests))))

(ert-deftest sumibi-decisions-scratch-is-plain-in-lisp-interaction-mode ()
  (sumibi-test--decisions-buffer
   (lisp-interaction-mode)
   (insert "korede jidouhenkan desu.")
   ;; Mock the name so an existing user's *scratch* is never renamed or edited.
   (cl-letf (((symbol-function 'buffer-name) (lambda (&optional _buffer) "*scratch*")))
            (let* ((snapshot (sumibi--decisions-snapshot 500))
                   (payload (json-parse-string
                             (decode-coding-string (sumibi--decisions-payload snapshot) 'utf-8)))
                   (input (gethash "input" payload)))
              (should (equal (plist-get snapshot :context) "plain"))
              (should (= (plist-get snapshot :start) (point-min)))
              (should (equal input (buffer-string)))
              (sumibi--decisions-submit snapshot)
              (sumibi-test--decisions-answer (car requests) 0.95)
              (should (= (length conversions) 1))
              (funcall (nth 4 (car conversions)) '("これで自動変換です") nil)
              (should (equal (buffer-string) "これで自動変換です。"))))))

(ert-deftest sumibi-decisions-other-lisp-interaction-buffers-remain-code ()
  (sumibi-test--decisions-buffer
   (lisp-interaction-mode)
   (insert "korede jidouhenkan desu.")
   (should (equal (plist-get (sumibi--decisions-snapshot 500) :context) "code"))))

(ert-deftest sumibi-decisions-auth-fixed-host-and-local-sources ()
  (let ((sumibi-api-key-source 'auth-source-keychain)
        (sumibi-provider 'gemini) (auth-sources '("unrelated")) seen)
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest args)
                 (setq seen (list args auth-sources))
                 (list (list :secret (lambda () "fake-openai-key"))))))
             (should (equal (sumibi--decisions-api-key) "fake-openai-key"))
             (should (equal (plist-get (car seen) :host) "api.openai.com"))
             (should (equal (plist-get (car seen) :user) "apikey"))
             (should (equal (cadr seen) '(macos-keychain-internet macos-keychain-generic)))
             (should (equal auth-sources '("unrelated"))))))

(ert-deftest sumibi-decisions-auth-does-not-use-foreign-environment-key ()
  (let ((process-environment (copy-sequence process-environment))
        (sumibi-api-key-source 'environment) (sumibi-provider 'gemini))
    (setenv "OPENAI_API_KEY" nil)
    (setenv "SUMIBI_AI_API_KEY" "foreign-key")
    (should-not (sumibi--decisions-api-key))
    (let ((sumibi-provider 'openai))
      (setenv "SUMIBI_AI_BASEURL" "https://example.invalid/v1")
      (should-not (sumibi--decisions-api-key))
      (setenv "SUMIBI_AI_BASEURL" nil)
      (should (equal (sumibi--decisions-api-key) "foreign-key")))
    (setenv "OPENAI_API_KEY" "explicit-openai-key")
    (should (equal (sumibi--decisions-api-key) "explicit-openai-key"))))

(ert-deftest sumibi-decisions-score-rejects-refusals-and-duplicates ()
  (dolist (answer '("{\"type\":\"refusal\",\"name\":\"convert_now\"}"
                    "{\"type\":\"predicate\",\"name\":\"convert_now\",\"probability\":1.1}"
                    "{\"type\":\"predicate\",\"name\":\"convert_now\",\"probability\":true}"
                    "{\"type\":\"predicate\",\"name\":\"other\",\"probability\":0.9}"))
    (should-error (sumibi--decisions-score (concat "{\"answers\":[" answer "]}"))))
  (should-error
   (sumibi--decisions-score
    "{\"answers\":[{\"type\":\"predicate\",\"name\":\"convert_now\",\"probability\":0.9},{\"type\":\"predicate\",\"name\":\"convert_now\",\"probability\":0.1}]}"))
  (should (= 0 (sumibi--decisions-score
                "{\"answers\":[{\"type\":\"predicate\",\"name\":\"convert_now\",\"probability\":0}]}"))))

(ert-deftest sumibi-decisions-readonly-overlay-added-during-request-is-stale ()
  (sumibi-test--decisions-buffer
   (insert "arigatou gozaimasu ")
   (sumibi-check-particle-trigger)
   (overlay-put (make-overlay (point-min) (point-max)) 'read-only t)
   (sumibi-test--decisions-answer (car requests) 0.95)
   (should-not conversions)
   (should (equal (buffer-string) "arigatou gozaimasu "))))

(ert-deftest sumibi-decisions-http-encodes-japanese-body-as-utf8-bytes ()
  (let ((response (generate-new-buffer " *utf8-http-test*")) seen seen-headers)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (&rest _args)
                 (setq seen url-request-data seen-headers url-request-extra-headers)
                 response)))
             (let ((cancel (sumibi--decisions-http-post
                            "https://example.invalid"
                            (list (cons "Authorization" (string-to-multibyte "Bearer fake-key")))
                            "日本語" 1 #'ignore)))
               (should-not (multibyte-string-p seen))
               (should (equal (decode-coding-string seen 'utf-8) "日本語"))
               (should-not (multibyte-string-p (cdar seen-headers)))
               (funcall cancel)))))

(ert-deftest sumibi-decisions-programming-comments-and-strings-are-prose ()
  (dolist (example '((emacs-lisp-mode ";;;arigatou gozaimasu " ";;;")
                     (emacs-lisp-mode "(message \"arigatou gozaimasu " "(message \"")
                     (python-mode "#arigatou gozaimasu " "#")
                     (python-mode "message = 'arigatou gozaimasu " "message = '")
                     (python-mode "message = \"\"\"arigatou gozaimasu " "message = \"\"\"")
                     (c-mode "/*arigatou gozaimasu " "/*")
                     (c-mode "//arigatou gozaimasu " "//")))
    (sumibi-test--decisions-buffer
     (funcall (nth 0 example))
     (insert (nth 1 example))
     (let ((snapshot (sumibi--decisions-snapshot 0)))
       (should (equal (plist-get snapshot :context) "plain"))
       (should (equal (plist-get snapshot :text) "arigatou gozaimasu "))
       (sumibi--decisions-submit snapshot)
       (sumibi-test--decisions-answer (car requests) 0.85)
       (funcall (nth 4 (car conversions)) '("ありがとうございます") nil)
       (should (equal (buffer-string) (concat (nth 2 example) "ありがとうございます")))))))

(ert-deftest sumibi-decisions-programming-code-remains-code ()
  (sumibi-test--decisions-buffer
   (emacs-lisp-mode)
   (insert "(setq arigatou ")
   (let* ((snapshot (sumibi--decisions-snapshot 0))
          (payload (json-parse-string
                    (decode-coding-string (sumibi--decisions-payload snapshot) 'utf-8))))
     (should (equal (plist-get snapshot :context) "code"))
     (should (equal (gethash "input" payload) "setq arigatou ")))))

(ert-deftest sumibi-decisions-english-string-waits-and-preserves-delimiters ()
  (sumibi-test--decisions-buffer
   (emacs-lisp-mode)
   (insert "(message \"Please review the report ")
   (save-excursion (insert "\")"))
   (sumibi-check-particle-trigger)
   (sumibi-test--decisions-answer (car requests) 0.1)
   (should-not conversions)
   (should (equal (buffer-string) "(message \"Please review the report \")"))))

(ert-deftest sumibi-decisions-multiline-string-preserves-opening-and-closing-code ()
  (sumibi-test--decisions-buffer
   (emacs-lisp-mode)
   (insert "(message \"first line\narigatou gozaimasu ")
   (save-excursion (insert "\")"))
   (sumibi-check-particle-trigger)
   (sumibi-test--decisions-answer (car requests) 0.85)
   (funcall (nth 4 (car conversions)) '("ありがとうございます") nil)
   (should (equal (buffer-string) "(message \"first line\nありがとうございます\")"))))

(ert-deftest sumibi-decisions-safe-event-logging ()
  (let ((log-buffer (generate-new-buffer " *decisions-test-log*"))
        (create-buffer (symbol-function 'get-buffer-create)))
    (unwind-protect
        (sumibi-test--decisions-buffer
         (let ((sumibi-decisions-debug t))
           (cl-letf (((symbol-function 'get-buffer-create)
                      (lambda (name &optional inhibit-buffer-hooks)
                        (if (equal name "*sumibi-debug*") log-buffer
                          (funcall create-buffer name inhibit-buffer-hooks)))))
                    (insert "arigatou gozaimasu ")
                    (sumibi-check-particle-trigger)
                    (sumibi-test--decisions-answer (car requests) 0.85)
                    (funcall (nth 4 (car conversions)) '("ありがとうございます") nil)
                    (sumibi--decisions-notice 'timeout))
           (with-current-buffer log-buffer
             (let ((log (buffer-string)))
               (dolist (line (split-string log "\n" t))
                 (should (string-match-p
                          "\\`[0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\.[0-9]\\{3\\} \\[Decisions\\] "
                          line)))
               (should (string-match-p "\\[Decisions\\] request=1" log))
               (should (string-match-p "score=0.850 threshold=0.800 action=convert" log))
               (should (string-match-p "conversion applying" log))
               (should (string-match-p "error=timeout" log))
               (should-not (string-match-p "arigatou\\|ありがとうございます\\|test-key\\|test-conversion-key" log))))))
      (kill-buffer log-buffer))))

(ert-deftest sumibi-decisions-logging-can-be-disabled ()
  (let ((sumibi-decisions-debug nil))
    (cl-letf (((symbol-function 'get-buffer-create)
               (lambda (_) (ert-fail "disabled logging created a buffer"))))
             (sumibi--decisions-log "request=%d" 1))))

(ert-deftest sumibi-decisions-trace-exposes-property-only-invalidation ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-debug t) (sumibi-decisions-debug-trace t) events)
     (cl-letf (((symbol-function 'sumibi--decisions-log)
                (lambda (format-string &rest args)
                  (push (apply #'format format-string args) events))))
              (sumibi-setup-auto-convert-hook)
              (let ((this-command 'self-insert-command) (last-command-event ?n))
                (sumibi--decisions-pre-command)
                (insert "n")
                (sumibi-check-particle-trigger)
                (sumibi--decisions-post-command))
              (let ((tick (buffer-chars-modified-tick)))
                (put-text-property (point-min) (point-max) 'face 'default)
                (should (= tick (buffer-chars-modified-tick))))
              (sumibi-test--decisions-answer (car requests) 0.95)
              (let ((log (mapconcat #'identity (nreverse events) "\n")))
                (should (string-match-p "reason=pre-command key=\"n\"" log))
                (should (string-match-p "reason=post-self-insert key=\"n\"" log))
                (should (string-match-p "reason=after-change.*chars-changed=nil" log))
                (should (string-match-p "generation=[0-9]+->[0-9]+" log))
                (should (string-match-p "check phase=decision-response.*text-same=t" log))
                (should (string-match-p "action=convert" log))
                (should (string-match-p "target-same=t" log))
                (should-not (string-match-p "test-key\\|test-conversion-key" log)))))))

(ert-deftest sumibi-decisions-trace-is-opt-in-and-respects-exclusions ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-debug t) events)
     (cl-letf (((symbol-function 'sumibi--decisions-log)
                (lambda (&rest args) (push args events))))
              (let ((sumibi-decisions-debug-trace nil))
                (sumibi--decisions-invalidate 'pre-command)
                (should-not events))
              (let ((sumibi-decisions-debug-trace t)
                    (buffer-file-name "/tmp/private.gpg"))
                (sumibi--decisions-invalidate 'after-change)
                (should-not events))))))

(ert-deftest sumibi-decisions-caller-log-never-prints-frame-arguments ()
  (cl-letf (((symbol-function 'backtrace-frames)
             (lambda (&optional _base)
               '((t sumibi--decisions-after-change (1 2 0))
                 (t insert ("private-input" "fake-api-key"))
                 (t diagnostic-edit ("private-argument"))
                 (t (closure (private-binding) () "private-body") nil)))))
           (let ((names (sumibi--decisions-caller-names)))
             (should (equal names
                            "sumibi--decisions-after-change <- insert <- diagnostic-edit <- <anonymous>"))
             (should-not (string-match-p "private\\|fake-api-key" names)))))

(defun sumibi-test--diagnostic-edit ()
  "Perform a temporary insertion/deletion for caller-trace verification."
  (save-excursion (insert "temporary") (delete-char -9)))

(ert-deftest sumibi-decisions-after-change-caller-identifies-temporary-editor ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-debug t) (sumibi-decisions-debug-trace t) events)
     (cl-letf (((symbol-function 'sumibi--decisions-log)
                (lambda (format-string &rest args)
                  (push (apply #'format format-string args) events))))
              (sumibi-setup-auto-convert-hook)
              (insert "nihongo.")
              (setq events nil)
              (sumibi-test--diagnostic-edit)
              (let ((log (mapconcat #'identity events "\n")))
                (should (string-match-p "after-change-caller generation=" log))
                (should (string-match-p "callers=.*sumibi-test--diagnostic-edit" log))
                (should (string-match-p "buffer=" log))
                (should-not (string-match-p "temporary\\|nihongo\\|test-key" log)))))))

(ert-deftest sumibi-decisions-input-payload-and-negative-decision ()
  (sumibi-test--decisions-buffer
   (insert "I will review the report ")
   (cl-letf (((symbol-function 'sumibi-is-english-text-p) (lambda (_) (ert-fail "legacy guard used")))
             ((symbol-function 'sumibi-has-sufficient-romaji-p) (lambda (_) (ert-fail "legacy guard used"))))
            (sumibi-check-particle-trigger))
   (let* ((request (car requests))
          (payload (json-parse-string (decode-coding-string (nth 2 request) 'utf-8)))
          (input (gethash "input" payload)))
     (should (equal (car request) sumibi-decisions-endpoint))
     (should (equal (gethash "model" payload) "gpt-6-luna"))
     (let ((question (aref (gethash "questions" payload) 0)))
       (should (equal (gethash "type" question) "predicate"))
       (should (equal (gethash "name" question) "convert_now"))
       (should (string-match-p "True criteria:" (gethash "instructions" question))))
     (should (equal input (buffer-string)))
     (sumibi-test--decisions-answer request 0.45)
     (should-not conversions)
     (should-not sumibi--decisions-inflight)
     (should (equal (buffer-string) "I will review the report ")))))

(ert-deftest sumibi-decisions-threshold-and-asynchronous-conversion ()
  (sumibi-test--decisions-buffer
   (buffer-enable-undo)
   (insert "arigatou gozaimasu ")
   (sumibi-check-particle-trigger)
   (sumibi-test--decisions-answer (car requests) 0.8)
   (should (equal (buffer-string) "arigatou gozaimasu "))
   (should (equal (caar conversions) "arigatou gozaimasu"))
   (funcall (nth 4 (car conversions)) '("ありがとうございます") nil)
   (should (equal (buffer-string) "ありがとうございます"))
   (should (= 1 (length sumibi-history-stack)))
   (should (equal (caar sumibi-henkan-kouho-list) "ありがとうございます"))
   (should (equal (car (car (last sumibi-henkan-kouho-list))) "arigatou gozaimasu "))
   (should-not sumibi--decisions-inflight)
   (undo-only 1)
   (should (equal (buffer-string) "arigatou gozaimasu "))))

(ert-deftest sumibi-decisions-below-threshold-preserves-input ()
  (sumibi-test--decisions-buffer
   (insert "ohayou gozaimasu ")
   (sumibi-check-particle-trigger)
   (sumibi-test--decisions-answer (car requests) 0.79)
   (should-not conversions)
   (should (equal (buffer-string) "ohayou gozaimasu "))))

(ert-deftest sumibi-decisions-stale-decision-retains-every-state ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (insert "arigatou ")
   (sumibi-check-particle-trigger)
   (let ((old (car requests)))
     (insert "g") (sumibi-check-particle-trigger)
     (insert "o") (sumibi-check-particle-trigger)
     (should (= 1 (length requests)))
     (sumibi-test--decisions-answer old 0.9)
     (should-not conversions)
     (should (= 2 (length requests)))
     (should (equal (plist-get sumibi--decisions-inflight :text) "arigatou g"))
     (sumibi-test--decisions-answer (car requests) 0.9)
     (should-not conversions)
     (should (= 3 (length requests)))
     (should (equal (plist-get sumibi--decisions-inflight :text) "arigatou go")))))

(ert-deftest sumibi-decisions-every-keystroke-is-scored-without-stale-conversion ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (let ((text "arigatou gozaimasu ") states)
     (dolist (character (string-to-list text))
       (sumibi--decisions-pre-command)
       (insert character)
       (sumibi-check-particle-trigger)
       (push (buffer-string) states))
     (should (= (length sumibi--decisions-pending) (1- (length text))))
     (setq states (nreverse states))
     (dolist (state states)
       (should (equal (plist-get sumibi--decisions-inflight :text) state))
       (sumibi-test--decisions-answer (car requests) 0.95)
       (unless (equal state text) (should-not conversions)))
     (should (= (length requests) (length text)))
     (should (= (length conversions) 1))
     (should-not sumibi--decisions-pending))))

(ert-deftest sumibi-decisions-queued-requests-respect-cap-and-stop ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-max-calls-per-buffer 2))
     (dolist (character '(?a ?b ?c))
       (insert character) (sumibi-check-particle-trigger))
     (should (= (length sumibi--decisions-pending) 1))
     (sumibi-test--decisions-answer (car requests) 0.1)
     (sumibi-test--decisions-answer (car requests) 0.1)
     (should (= (length requests) 2))
     (should-not sumibi--decisions-pending))
   (sumibi-decisions-reset-call-count)
   (insert "d") (sumibi-check-particle-trigger)
   (insert "e") (sumibi-check-particle-trigger)
   (should sumibi--decisions-pending)
   (sumibi--decisions-stop)
   (should-not sumibi--decisions-pending)))

(ert-deftest sumibi-decisions-stale-conversion-does-not-edit ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (sumibi-test--decisions-answer (car requests) 0.9)
   (let ((callback (nth 4 (car conversions))))
     (insert "gozaimasu ") (sumibi-check-particle-trigger)
     (funcall callback '("ありがとう") nil)
     (should (equal (buffer-string) "arigatou gozaimasu "))
     (should-not sumibi-history-stack))))

(ert-deftest sumibi-decisions-cursor-movement-invalidates-decision ()
  (sumibi-test--decisions-buffer
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (sumibi--ambient-pre-command-cancel)
   (backward-char)
   (sumibi-test--decisions-answer (car requests) 0.9)
   (should-not conversions)))

(ert-deftest sumibi-decisions-programmatic-edits-invalidate-decision ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (save-excursion (goto-char (point-min)) (delete-char 1) (insert "x"))
   (sumibi-test--decisions-answer (car requests) 0.9)
   (should-not conversions)))

(ert-deftest sumibi-decisions-disabled-or-selecting-ignores-response ()
  (dolist (setting '(disabled selecting backend))
    (sumibi-test--decisions-buffer
     (insert "arigatou ") (sumibi-check-particle-trigger)
     (pcase setting
       ('disabled (setq sumibi-ambient-enable nil))
       ('selecting (setq sumibi-select-mode t))
       ('backend (setq sumibi-ambient-backend 'rules)))
     (sumibi-test--decisions-answer (car requests) 0.9)
     (should-not conversions))))

(ert-deftest sumibi-decisions-settings-change-invalidates-response ()
  (sumibi-test--decisions-buffer
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (let ((sumibi-decisions-threshold 0.9))
     (sumibi-test--decisions-answer (car requests) 0.95)
     (should-not conversions))))

(ert-deftest sumibi-decisions-excluded-buffers-never-send ()
  (dolist (context '(shell gpg minibuffer readonly selecting region disabled))
    (sumibi-test--decisions-buffer
     (insert "watashiwa ")
     (pcase context
       ('shell (setq major-mode 'shell-mode))
       ('gpg (setq buffer-file-name "/tmp/decisions-test.gpg"))
       ('readonly (setq buffer-read-only t))
       ('selecting (setq sumibi-select-mode t))
       ('region (set-mark (point-min)) (setq transient-mark-mode t mark-active t))
       ('disabled (setq sumibi-ambient-enable nil)))
     (cl-letf (((symbol-function 'minibufferp) (lambda (&optional _) (eq context 'minibuffer))))
              (sumibi-check-particle-trigger))
     (should-not requests))))

(ert-deftest sumibi-decisions-convertible-characters-send ()
  (dolist (text '("3.14" "123 " "yatta!"))
    (sumibi-test--decisions-buffer
     (insert text) (sumibi-check-particle-trigger)
     (should (= 1 (length requests))))))

(ert-deftest sumibi-decisions-no-roman-target-skips ()
  (dolist (text '("yatta！" "日本語" "hai\n"))
    (sumibi-test--decisions-buffer
     (insert text) (sumibi-check-particle-trigger)
     (should-not requests))))

(ert-deftest sumibi-decisions-transient-popup-edits-accept-restored-target ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (insert "nihongo.") (sumibi-check-particle-trigger)
   (let ((generation sumibi--decisions-generation)
         (tick (buffer-chars-modified-tick)))
     ;; auto-complete's popup inserts and then removes temporary characters.
     (save-excursion (insert " popup text") (delete-region (- (point) 11) (point)))
     (should (> sumibi--decisions-generation generation))
     (should (> (buffer-chars-modified-tick) tick)))
   (sumibi-test--decisions-answer (car requests) 1.0)
   (should conversions)
   (save-excursion (insert " popup text") (delete-region (- (point) 11) (point)))
   (funcall (nth 4 (car conversions)) '("日本語") nil)
   (should (equal (buffer-string) "日本語。"))))

(ert-deftest sumibi-decisions-range-must-match-even-with-identical-text ()
  (sumibi-test--decisions-buffer
   (insert "nihongo>nihongo") (sumibi-check-particle-trigger)
   (should (equal (plist-get sumibi--decisions-inflight :text) "nihongo"))
   (set-marker (mark-marker) (1- (point)))
   (sumibi-test--decisions-answer (car requests) 0.95)
   (should-not conversions)))

(ert-deftest sumibi-decisions-range-reuses-manual-stop-and-prefix-rules ()
  (dolist (input '("prefix>nihongo." "  - nihongo." "(nihongo." "日本語nihongo."))
    (sumibi-test--decisions-buffer
     (insert input)
     (let* ((end (point)) (start (+ end (sumibi-skip-chars-backward)))
            (snapshot (sumibi--decisions-snapshot 0)))
       (should (= start (plist-get snapshot :start)))
       (should (equal (buffer-substring-no-properties start end)
                      (plist-get snapshot :text)))))))

(ert-deftest sumibi-decisions-range-reuses-markdown-and-auto-fill-rules ()
  (dolist (markdown '(nil t))
    (sumibi-test--decisions-buffer
     (let ((auto-fill-function (unless markdown #'do-auto-fill)))
       (insert (if markdown "# nihongo(test)." "nihongo\ndesu."))
       (cl-letf (((symbol-function 'sumibi-in-markdown-mode-p) (lambda () markdown)))
         (let* ((end (point))
                (start (+ end (if markdown
                                 (sumibi-skip-chars-backward-markdown)
                               (sumibi-skip-chars-backward))))
                (snapshot (sumibi--decisions-snapshot 0)))
           (should (= start (plist-get snapshot :start)))
           (should (equal (buffer-substring-no-properties start end)
                          (plist-get snapshot :text)))))))))

(ert-deftest sumibi-decisions-popup-still-present-rejects-response ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (insert "nihongo.") (sumibi-check-particle-trigger)
   (insert " popup")
   (sumibi-test--decisions-answer (car requests) 1.0)
   (should-not conversions)))

(ert-deftest sumibi-decisions-context-limit-skips-without-truncating ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-decisions-max-context-length 5))
     (insert "arigatou ") (sumibi-check-particle-trigger)
     (should-not requests))))

(ert-deftest sumibi-decisions-key-and-call-limit-preserve-manual-conversion ()
  (sumibi-test--decisions-buffer
   (insert "arigatou ")
   (setenv "OPENAI_API_KEY" nil)
   (sumibi-check-particle-trigger)
   (should-not requests)
   (setenv "OPENAI_API_KEY" "test-key")
   (setq sumibi--decisions-call-count 1000)
   (sumibi-check-particle-trigger)
   (should-not requests)
   (sumibi-decisions-reset-call-count)
   (sumibi-check-particle-trigger)
   (should (= 1 (length requests)))))

(ert-deftest sumibi-decisions-malformed-and-http-errors-preserve-input ()
  (dolist (body '("{}" "garbage" "{\"answers\":{\"convert_now\":{\"noul\":2}}}"))
    (sumibi-test--decisions-buffer
     (insert "arigatou ") (sumibi-check-particle-trigger)
     (funcall (nth 4 (car requests)) body nil)
     (should-not conversions)
     (should-not sumibi--decisions-inflight)
     (should (equal (buffer-string) "arigatou "))))
  (sumibi-test--decisions-buffer
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (funcall (nth 4 (car requests)) nil 'http-error)
   (should-not conversions)
   (should-not sumibi--decisions-inflight)))

(ert-deftest sumibi-decisions-conversion-failure-preserves-space ()
  (sumibi-test--decisions-buffer
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (sumibi-test--decisions-answer (car requests) 0.9)
   (funcall (nth 4 (car conversions)) nil 'timeout)
   (should (equal (buffer-string) "arigatou "))
   (should-not sumibi--decisions-inflight)))

(ert-deftest sumibi-decisions-punctuation-converts-without-debounce ()
  (sumibi-test--decisions-buffer
   (insert "ashitamo ikimasuka?")
   (sumibi-check-particle-trigger)
   (should (= 1 (length requests)))
   (should (= (plist-get sumibi--decisions-inflight :pause) 0))
   (should-not sumibi--decisions-timer)
   (sumibi-test--decisions-answer (car requests) 0.9)
   (should (equal (caar conversions) "ashitamo ikimasuka"))
   (funcall (nth 4 (car conversions)) '("明日も行きますか") nil)
   (should (equal (buffer-string) "明日も行きますか？"))))

(ert-deftest sumibi-decisions-next-key-cancels-punctuation-observation ()
  (sumibi-test--decisions-buffer
   (insert "hai,") (sumibi-check-particle-trigger)
   (sumibi--ambient-pre-command-cancel)
   (should-not sumibi--decisions-timer)
   (should (= 1 (length requests)))))

(ert-deftest sumibi-decisions-deletion-observes-new-state ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (insert "arigatou x")
   (sumibi--ambient-pre-command-cancel)
   (delete-char -1)
   (let ((this-command 'delete-backward-char))
     (sumibi--decisions-post-command))
   (should (= 1 (length requests)))
   (should (equal (plist-get sumibi--decisions-inflight :key) "BACKSPACE"))
   (should (equal (plist-get sumibi--decisions-inflight :text) "arigatou "))))

(ert-deftest sumibi-decisions-wrapped-self-insert-does-not-submit-twice ()
  (sumibi-test--decisions-buffer
   (sumibi-setup-auto-convert-hook)
   (sumibi--ambient-pre-command-cancel)
   (insert "a")
   (sumibi-check-particle-trigger)
   (let ((this-command 'org-self-insert-command))
     (sumibi--decisions-post-command))
   (should (= 1 (length requests)))
   (should-not sumibi--decisions-pending)))

(ert-deftest sumibi-decisions-punctuation-ignores-rule-delay ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-ambient-punctuation-delay 30))
     (insert "hai,") (sumibi-check-particle-trigger)
     (should (= 1 (length requests)))
     (should (= (plist-get sumibi--decisions-inflight :pause) 0))
     (sumibi-test--decisions-answer (car requests) 0.1)
     (should-not sumibi--decisions-timer)
     (should-not sumibi--decisions-inflight))))

(ert-deftest sumibi-decisions-linguistic-input-independent-of-metadata ()
  (sumibi-test--decisions-buffer
   (let* ((plain (list :text "nihongo" :key "o" :context "plain" :pause 0))
          (code (list :text "nihongo" :key "." :context "code" :pause 1000))
          (payload (json-parse-string
                    (decode-coding-string (sumibi--decisions-payload plain) 'utf-8)))
          (instructions (gethash "instructions" (aref (gethash "questions" payload) 0))))
     (should (equal (sumibi--decisions-payload plain) (sumibi--decisions-payload code)))
     (should (equal (gethash "input" payload) "nihongo"))
     (should (string-match-p "incomplete prefix" instructions))
     (should (string-match-p "Do not judge whether now is a good time to convert" instructions))
     (should-not (string-match-p "500" instructions)))))

(ert-deftest sumibi-decisions-no-duplicate-punctuation-from-converter ()
  (sumibi-test--decisions-buffer
   (insert "ashitamo ikimasuka?")
   (let ((snapshot (sumibi--decisions-snapshot 500)))
     (setq sumibi--decisions-inflight snapshot)
     (sumibi--decisions-convert snapshot)
     (funcall (nth 4 (car conversions)) '("明日も行きますか？") nil)
     (should (equal (buffer-string) "明日も行きますか？")))))

(ert-deftest sumibi-decisions-readonly-text-never-sends ()
  (sumibi-test--decisions-buffer
   (insert (propertize "arigatou " 'read-only t))
   (sumibi-check-particle-trigger)
   (should-not requests))
  (sumibi-test--decisions-buffer
   (insert "arigatou ")
   (overlay-put (make-overlay (point-min) (point-max)) 'read-only t)
   (sumibi-check-particle-trigger)
   (should-not requests)))

(ert-deftest sumibi-decisions-nonselected-buffer-response-is-stale ()
  (sumibi-test--decisions-buffer
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (let ((noninteractive nil))
     (sumibi-test--decisions-answer (car requests) 0.9)
     (should-not conversions))))

(ert-deftest sumibi-decisions-http-cancel-before-response-is-silent ()
  (let ((response (generate-new-buffer " *decisions-cancel-test*")) callback results)
    (cl-letf (((symbol-function 'url-retrieve)
               (lambda (_url cb &rest _args) (setq callback cb) response)))
             (let ((cancel (sumibi--decisions-http-post "https://example.invalid" nil "{}" 1
                                                        (lambda (&rest result) (push result results)))))
               (funcall cancel)
               (should-not (buffer-live-p response))
               (with-temp-buffer (funcall callback '(:error cancelled)))
               (should-not results)))))

(ert-deftest sumibi-decisions-mode-disable-cancels-work-and-hooks ()
  (sumibi-test--decisions-buffer
   (let ((cancelled nil))
     (setq sumibi--decisions-cancel-request (lambda () (setq cancelled t)))
     (sumibi-setup-auto-convert-hook)
     (should (memq #'sumibi--decisions-after-change after-change-functions))
     (sumibi-mode -1)
     (should cancelled)
     (should-not (memq #'sumibi--decisions-after-change after-change-functions)))))

(ert-deftest sumibi-decisions-initializes-persisted-history-once ()
  (sumibi-test--decisions-buffer
   (let ((sumibi-init nil) (loads 0))
     (cl-letf (((symbol-function 'sumibi-load-history-from-file)
                (lambda () (cl-incf loads))))
              (insert "arigatou ") (sumibi-check-particle-trigger)
              (sumibi-test--decisions-answer (car requests) 0.9)
              (should sumibi-init)
              (should (= loads 1))))))

(ert-deftest sumibi-decisions-ctrl-j-restores-candidate-selection ()
  (sumibi-test--decisions-buffer
   (insert "arigatou gozaimasu ") (sumibi-check-particle-trigger)
   (sumibi-test--decisions-answer (car requests) 0.9)
   (funcall (nth 4 (car conversions)) '("ありがとうございます" "有難うございます") nil)
   (sumibi-rK-trans)
   (should sumibi-select-mode)
   (should (= 3 sumibi-cand-len))
   (sumibi-select-cancel)
   (should (equal (buffer-string) "ありがとうございます"))))

(ert-deftest sumibi-decisions-killed-buffer-response-is-ignored ()
  (sumibi-test--decisions-buffer
   (insert "arigatou ") (sumibi-check-particle-trigger)
   (let ((buffer (current-buffer)) (request (car requests)))
     (kill-buffer buffer)
     (sumibi-test--decisions-answer request 0.9)
     (should-not conversions))))

(ert-deftest sumibi-decisions-http-timeout-completes-once-and-cleans-up ()
  (let ((response (generate-new-buffer " *decisions-http-test*"))
        timer-function http-callback results)
    (unwind-protect
        (cl-letf (((symbol-function 'url-retrieve)
                   (lambda (_url callback &rest _args)
                     (setq http-callback callback) response))
                  ((symbol-function 'run-with-timer)
                   (lambda (_seconds _repeat callback &rest _args)
                     (setq timer-function callback) nil)))
                 (sumibi--decisions-http-post "https://example.invalid" nil "{}" 1
                                              (lambda (body error) (push (list body error) results)))
                 (funcall timer-function)
                 (should (equal results '((nil timeout))))
                 (should-not (buffer-live-p response))
                 (with-temp-buffer (funcall http-callback '(:error connection-failed)))
                 (should (= 1 (length results))))
      (when (buffer-live-p response) (kill-buffer response)))))

(ert-deftest sumibi-decisions-http-success-returns-body-and-cancellation-is-silent ()
  (let ((response (generate-new-buffer " *decisions-http-test*")) callback results)
    (unwind-protect
        (cl-letf (((symbol-function 'url-retrieve)
                   (lambda (_url cb &rest _args) (setq callback cb) response)))
                 (let ((cancel (sumibi--decisions-http-post
                                "https://example.invalid" nil "{}" 1
                                (lambda (body error) (push (list body error) results)))))
                   (with-current-buffer response
                     (setq-local url-http-response-status 200)
                     (insert "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"ok\":true}")
                     (funcall callback nil))
                   (should (equal results '(("{\"ok\":true}" nil))))
                   (funcall cancel)
                   (should (= 1 (length results)))
                   (should-not (buffer-live-p response))))
      (when (buffer-live-p response) (kill-buffer response)))))

(ert-deftest sumibi-decisions-existing-conversion-prompt-safe-async-path ()
  (let (handler result)
    (cl-letf (((symbol-function 'sumibi--decisions-http-post)
               (lambda (_url _headers _body _timeout cb) (setq handler cb) #'ignore))
              ((symbol-function 'sumibi-get-api-key) (lambda () "test-key")))
             (with-temp-buffer
               (insert "arigatou gozaimasu")
               (let ((cancel (sumibi-roman-to-kanji-with-surrounding
                              (buffer-string) (buffer-string) 1 nil
                              (lambda (strings error) (setq result (list strings error))))))
                 (should (functionp cancel))
                 (funcall handler "{\"choices\":[{\"message\":{\"content\":\"ありがとうございます\"}}]}" nil)
                 (should (equal result '(("ありがとうございます") nil)))
                 (should (equal (buffer-string) "arigatou gozaimasu")))))))

(provide 'sumibi-decisions-test)
;;; sumibi-decisions-test.el ends here
