# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/engine_builder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotocol/engine_builder.proto\x12\x04mozc\"\xb8\x01\n\x13\x45ngineReloadRequest\x12\x39\n\x0b\x65ngine_type\x18\x01 \x02(\x0e\x32$.mozc.EngineReloadRequest.EngineType\x12\x11\n\tfile_path\x18\x02 \x02(\t\x12\x14\n\x0cmagic_number\x18\x04 \x01(\t\x12\x10\n\x08priority\x18\x05 \x01(\x05\"%\n\nEngineType\x12\x0b\n\x07\x44\x45SKTOP\x10\x00\x12\n\n\x06MOBILE\x10\x01J\x04\x08\x03\x10\x04\"\xb9\x02\n\x14\x45ngineReloadResponse\x12\x31\n\x06status\x18\x01 \x02(\x0e\x32!.mozc.EngineReloadResponse.Status\x12*\n\x07request\x18\x02 \x01(\x0b\x32\x19.mozc.EngineReloadRequest\"\xc1\x01\n\x06Status\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\x10\n\x0cRELOAD_READY\x10\x01\x12\x0c\n\x08RELOADED\x10\x02\x12\x13\n\x0f\x41LREADY_RUNNING\x10\x03\x12\x1b\n\x17\x45NGINE_VERSION_MISMATCH\x10\x04\x12\x10\n\x0c\x44\x41TA_MISSING\x10\x05\x12\x0f\n\x0b\x44\x41TA_BROKEN\x10\x06\x12\x10\n\x0cMMAP_FAILURE\x10\x07\x12\x11\n\rUNKNOWN_ERROR\x10\t*\x0fINSTALL_FAILUREBD\n.org.mozc.android.inputmethod.japanese.protobufB\x12ProtoEngineBuilder')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.engine_builder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n.org.mozc.android.inputmethod.japanese.protobufB\022ProtoEngineBuilder'
  _ENGINERELOADREQUEST._serialized_start=40
  _ENGINERELOADREQUEST._serialized_end=224
  _ENGINERELOADREQUEST_ENGINETYPE._serialized_start=181
  _ENGINERELOADREQUEST_ENGINETYPE._serialized_end=218
  _ENGINERELOADRESPONSE._serialized_start=227
  _ENGINERELOADRESPONSE._serialized_end=540
  _ENGINERELOADRESPONSE_STATUS._serialized_start=347
  _ENGINERELOADRESPONSE_STATUS._serialized_end=540
# @@protoc_insertion_point(module_scope)
