# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/segmenter_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotocol/segmenter_data.proto\x12\x0emozc.converter\"S\n\x15SegmenterDataSizeInfo\x12\x1c\n\x10\x63ompressed_lsize\x18\x01 \x01(\x04\x42\x02\x30\x01\x12\x1c\n\x10\x63ompressed_rsize\x18\x02 \x01(\x04\x42\x02\x30\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.segmenter_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEGMENTERDATASIZEINFO.fields_by_name['compressed_lsize']._options = None
  _SEGMENTERDATASIZEINFO.fields_by_name['compressed_lsize']._serialized_options = b'0\001'
  _SEGMENTERDATASIZEINFO.fields_by_name['compressed_rsize']._options = None
  _SEGMENTERDATASIZEINFO.fields_by_name['compressed_rsize']._serialized_options = b'0\001'
  _SEGMENTERDATASIZEINFO._serialized_start=49
  _SEGMENTERDATASIZEINFO._serialized_end=132
# @@protoc_insertion_point(module_scope)
